### ISSUE TITLE
Brick to Brick Bluetooth communication support

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-ev3#43]
## Design
- [ ] Compare LabView / RobotC / Switf / YouTube
- [ ] API design

## Implementation
- [ ] Separate project
- [ ] TypeScript / Blocks API
- [ ] Hardware support
- [ ] Simulator support
- [ ] Documentation
- [ ] Examples

**Comment by Beat-YT** [comment]
Why is that closed?
