### ISSUE TITLE
A few broken links in the different lokalized languages. 

### ISSUE THREAD

**Issue by KitNeel** [microsoft/pxt-ev3#771]
**Describe the bug**
Some of the links in the different pages are broke after localaization. See overview and please fix. When fixed we can "open" for the five new language. 

[MakeCode Tranlation Broken Links.xlsx](https://github.com/Microsoft/pxt-ev3/files/2347984/MakeCode.Tranlation.Broken.Links.xlsx)

**Comment by ganicke** [comment]
I think the localization changes tagged in issue have been addressed in and amongst the PRs referenced. Closing this now. Anything new can go into a new issue.
