### ISSUE TITLE
Unable to delete MakeCode files on the Brick

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-ev3#772]
Users unable to delete MakeCode program files on the EV brick.  @riknoll or @guillaumejenkins please add more detail if you have it.

**Comment by abchatra** [comment]
Bug - Feedback from FLL team which visited us.

**Comment by Technonati** [comment]
When will MakeCode Mindstorms have the basic file management functionality of the EV3 LabView environment?

You can't delete programs without re-flashing the brick. 
When program ends, the EV3 brick doesn't go back to the tab-picker view on the brick.
You can't create project folders to store programs in.

I am willing to accept that I may have totally missed the instructions to do this and don't understand MakeCode Mindstorms, but I don't think I have.

It is impossible to actually use the MakeCode Mindstorms for programming the EV3 to do anything robotic unless you can actually delete programs, which would actually mean being able to put programs into their own Project folders (which also could be deleted).

Unless I am missing something, MakeCode Mindstorms doesn't even have the basic EV3 brick programmability, like it does in the EV3-G environment.

MakeCode Mindstorms has lots of potential.

Or possibly, I am just an idiot.

**Comment by abchatra** [comment]
Unable to delete the program is a valid issue @Technonati Thanks for the feedback. 

Unfortunately this is the issue with the lego ev3 brick runtime itself and not MakeCode. We have communicated this to Lego education team and need to wait for the fix from them. 

@KitNeel @Jaqster

**Comment by Technonati** [comment]
Got it. I went through every closed post and found the one discussing this and having to flash the brick. One point - you don't have to downgrade the firmware, you only have to reflash it with 1.10E, but it has to be done from LabView. I can't make it work from the web-based firmware update on either my Mac or my Windows machine.

Can I ask about why when you drag a program onto the brick, it runs immediately? Also when a program finishes running, the brick doesn't go back to the Tab View? Am I missing something?

**Comment by maximmasterr** [comment]
@Technonati 
To delete program on brick you can use ev3 explorer from ev3basic or my explorer3
If you wnat to exit from program use `control.reset()`

**Comment by mmoskal** [comment]
For anyone tracking this - there is a workaround here https://makecode.mindstorms.com/fll#why-can-t-i-delete-my-program-uf2-files-from-the-brick-
