### ISSUE TITLE
Showport block do not show ports

### ISSUE THREAD

**Issue by KitNeel** [microsoft/pxt-ev3#823]
**Describe the bug**
When using the "ShowPorts" block, the emulator does not respond to the showports block. The EV3 block does sometimes show the right ports in the display but not always.

The user can on the EV3 brick use the built-in ports overview, but that is not the intention. The ShowPorts block don't seem to work as intended.

See screen shots: 

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/40029678/48482980-784a7100-e812-11e8-99fe-bcc34de6ae73.png">

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/40029678/48482996-80a2ac00-e812-11e8-865f-28d1f83c07b8.png">

**Comment by pelikhan** [comment]
Fixed.
