### ISSUE TITLE
Up / down bumped events can't be used when using console

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt-ev3#827]
**Describe the bug**
The up / down button bumped events are not hooked up and do nothing. 

**To Reproduce**
1. Try the following script: https://makecode.com/_cP3VwL2PmgLz
2. Try to use the up and down buttons, only the other buttons show the bumped event. 

**Expected behavior**
All buttons should show pressed, bumped, released.

**Comment by pelikhan** [comment]
Won't fix i suppose.
