### ISSUE TITLE
Gyro rate isn't supported in SIM

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt-ev3#829]
**Describe the bug**
If you use the gyro momentarily in the sim, it becomes unusable.

**To Reproduce**
1. Try the following code which momentarily sets the motor speed to the gyro rate: 
```
brick.buttonUp.onEvent(ButtonEvent.Pressed, function () {
    motors.mediumA.run(sensors.gyro2.angle())
})
```
2. After clicking on button up, you will no longer be able to manipulate the gyro rate from the sim.

**Expected behavior**
Be able to change the gyro rate at any point.

**Comment by pelikhan** [comment]
Fixed.
