### ISSUE TITLE
Make it possible to write data to files

### ISSUE THREAD

**Issue by THEb0nny** [microsoft/pxt-ev3#840]
There is a need to store data and work with them through a text file in the memory of the controller.

**Comment by pelikhan** [comment]
Have you tried adding the “storage” extension?

**Comment by THEb0nny** [comment]
> Have you tried adding the “storage” extension?

Is there such a thing? Need a link to this project ...

**Comment by THEb0nny** [comment]
> Have you tried adding the “storage” extension?


Какая ссылка на это расширение?
Kakaya ssylka na eto rasshireniye?
31/5000
What is the link to this extension?
Отправить отзыв
История
Сохранено
Сообщества

**Comment by abchatra** [comment]
@pelikhan what storage are you referring to?

**Comment by pelikhan** [comment]
storage package

**Comment by abchatra** [comment]
I don't see any storage package appearing when I search in extensions.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-ev3/tree/master/libs/storage

**Comment by maximmasterr** [comment]
Cannot connect repository using link above.
So I coppied files to my own repository and connect it using maximmasterr/pxt-ev3-storage
But I think that is not good way, so it is better to include it to dependency of ev3

**Comment by THEb0nny** [comment]
> Cannot connect repository using link above.
> So I coppied files to my own repository and connect it using maximmasterr/pxt-ev3-storage
> But I think that is not good way, so it is better to include it to dependency of ev3

I could not add. Please go to discord makecode for a discussion.

**Comment by pelikhan** [comment]
In /beta.
