### ISSUE TITLE
Motors not reaching full power when starting with under high load

### ISSUE THREAD

**Issue by acesTech** [microsoft/pxt-ev3#843]
When the starting torque is high due to robot weight or friction from large tracks, the motors never reach full power or even a realistic percentage like 70%, instead the never exceeds 20%. This issue has show up on multiple bots, and the only solution I have found is by starting by incrementing the power till it is at max, however this only gets it to full speed momentarily as any change in the motors drops it back down below 20%.

**Comment by pelikhan** [comment]
We have added the ability to specify an acceleration ramp that should help with this. Otherwise, please provide a way to reproduce the issue.
