### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by shuhanxu** [Microsoft/pxt-ev3#845]
**Describe the bug**
Fail to start local server. I follow the instruction and build pxt and pxt-common-packages. When i run pxt serve ( also pxt serve --local and --cloud). It compiles but the javascript has an exception.

**To Reproduce**
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at patchAppTarget (pxtapp.js:1783)
    at Object.setAppTarget (pxtapp.js:1678)
    at Object.setupAppTarget (main.js:16081)
    at HTMLDocument.<anonymous> (main.js:3427)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Chrome
 - Version 68.0.3440.106

**Comment by abchatra** [comment]
We don't support issues on local serve.
