### ISSUE TITLE
Function parameters

### ISSUE THREAD

**Issue by pinwc4** [microsoft/pxt-ev3#855]
Please add the ability to pass parameters and return a result to functions created within the block code.  This feature has recently been added to the microbit fork of makecode and would be very useful for anyone wanting to make their own functions.

**Comment by THEb0nny** [comment]
+100500

**Comment by tiestapistics** [comment]
+1

**Comment by abchatra** [comment]
Sure. We have a design to pass parameters.

**Comment by THEb0nny** [comment]
> Sure. We have a design to pass parameters.

So this is realized in the future? What project is pelikhan doing now?

**Comment by pelikhan** [comment]
Function parameters available in /beta
