### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by maximmasterr** [microsoft/pxt-ev3#862]
This feature related to create robots that communicates beetwen each one over bluetooth

### Solution
Built-in feature or extension to support communication over bluetooth beetwen two or more ev3
```js
//Example for sending string to ev3 with name Ev3-1
bluetooth.send('Ev3-1','Example string')

//Example of recieving data
bluetooth.on('data',(a=data)=>console.log(data))
```

### Alternatives
Other way to comunicate beetwen bricks

**Comment by abchatra** [comment]
Please give a clear description of the feature request. Use feature request template for filing issues.

**Comment by maximmasterr** [comment]
This feature related to create robots that communicates beetwen each one over bluetooth

### Solution
Built-in feature or extension to support communication over bluetooth beetwen two or more ev3
```js
//Example for sending string to ev3 with name Ev3-1
bluetooth.send('Ev3-1','Example string')

//Example of recieving data
bluetooth.on('data',(a=data)=>console.log(data))
```

### Alternatives
Other way to comunicate beetwen bricks

**Comment by maximmasterr** [comment]
Need to update compilation method add -lbluetooth

**Comment by maximmasterr** [comment]
Are you going to release this

**Comment by pelikhan** [comment]
Unlikely that we implement this feature this year but we do take pull requests.

**Comment by pelikhan** [comment]
See https://makecode.mindstorms.com/bluetooth

**Comment by maximmasterr** [comment]
Not I mean communication beetwen robots, not between robot and computer, reopen ut

**Comment by maximmasterr** [comment]
Reopen

**Comment by Beat-YT** [comment]
Yea
