### ISSUE TITLE
Battery parameters

### ISSUE THREAD

**Issue by maximmasterr** [microsoft/pxt-ev3#874]
Description to get battery **voltage**, current, motorCurrent

getBatteryInfo return also voltage and current and motorCurrent
like that: 
`{ voltage: number, current: number, motorCurrent: number, temp: number }`

**Comment by maximmasterr** [comment]
> @maximmasterr could you prep a PR?

Yes

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt-ev3/pull/903

**Comment by pelikhan** [comment]
In /beta
