### ISSUE TITLE
Upload over bluetoth

### ISSUE THREAD

**Issue by maximmasterr** [microsoft/pxt-ev3#902]
Upload over bluetooth without other program on local based edition will be very useful. Realise like hid

**Comment by pelikhan** [comment]
New developments... https://forum.makecode.com/t/can-i-download-the-codes-to-ev3-via-bluetooth/501/4

**Comment by pelikhan** [comment]
Supported using web serial. See https://makecode.mindstorms.com/bluetooth.

**Comment by dmstewart42** [comment]
Heads up that some things in the web serial API are renamed in Chrome 86:

https://bugs.chromium.org/p/chromium/issues/detail?id=884928#c124
