### ISSUE TITLE
Stop at Object Tutorial - breaking all tutorials!

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-ev3#959]
Repro - From the Home Page, open the 'Stop at Object' tutorial under the Touch Sensor Tutorials.  Reproduces on Chrome, Edge, IE and Safari.

Behavior - Error message: "Oops, an error occurred as we were loading the tutorial."  Then any other tutorial you open fails to load correctly.  Must reload the page.

![StopAtObject](https://user-images.githubusercontent.com/22108954/69362604-aba0b680-0c43-11ea-821e-f589fda5663a.png)

![LegoTutorial](https://user-images.githubusercontent.com/22108954/69362616-b0fe0100-0c43-11ea-97e1-d167933529e3.jpg)

**Comment by Jordmac12345** [comment]
I am having this issue with a few of my students. What was the solution? Thanks.
