### ISSUE TITLE
There is no way to switch the type of engines

### ISSUE THREAD

**Issue by THEb0nny** [microsoft/pxt-ev3#981]
**Describe the bug**
There is no way to switch the type of engines. This is manifested in languages other than English. On stable and beta.

**To Reproduce**
Video https://drive.google.com/open?id=1ZUOegPX5_n17kL_yu1nxge1N41kjg435

**Expected behavior**
Must open a list.

**Comment by MKleinSB** [comment]
@THEb0nny Did you translate large motor / medium motor / large motors ?

**Comment by THEb0nny** [comment]
@MKleinSB I originally translated. Later deleted the translation. When I recorded a video with a bug, there was no translation. Then he added again.

**Comment by MKleinSB** [comment]
@pelikhan
once you translated  large motor / medium motor / large motors you cannot change the motortype any more. 
The Blocks hangs on the pointer if you klick at the motortype and you can´t get rid of it.
So there sould be a Warning not to translate the string or the possibility to translate.
![Unbenannt](https://user-images.githubusercontent.com/37311672/77395404-c9bd2580-6da1-11ea-8965-516d25219aac.png)

**Comment by THEb0nny** [comment]
This method does not work for me. I cleaned the cache in Chrome.

**Comment by THEb0nny** [comment]
Chrome shows not translated words, but an edge with chromium translated ...

**Comment by THEb0nny** [comment]
@pelikhan need your decision...
