### ISSUE TITLE
Bluetooth does not work

### ISSUE THREAD

**Issue by THEb0nny** [microsoft/pxt-ev3#998]
I tried to load the bluetooth code into EV3. But now it cannot be done. An error is always thrown. Try it yourself. Something might have been updated in Chrome.
@pelikhan

**Comment by pelikhan** [comment]
I'll take a peek next week.

**Comment by THEb0nny** [comment]
@pelikhan hi, have you looked?

**Comment by THEb0nny** [comment]
@pelikhan https://github.com/microsoft/pxt-ev3/issues/902#issuecomment-674217648

**Comment by THEb0nny** [comment]
@pelikhan it turned out that with the bluetooth connection?

**Comment by THEb0nny** [comment]
@pelikhan have you seen why bluetooth does not work?

**Comment by dmitryaleshin** [comment]
The project is death but problem exists. I've attempted to create a PR with fix but have no proper rights.

**Comment by THEb0nny** [comment]
> The project is death but problem exists. I've attempted to create a PR with fix but have no proper rights.

hello, I support the project, my changes are accepted, a new version is added.

I have looked at this problem myself. The problem on all platforms is in makecode, but the developers have no plans to fix it. For example, in microbit it is also impossible to fill in the firmware in the same way.

**Comment by THEb0nny** [comment]
I didn't understand that the second part

**Comment by dmitryaleshin** [comment]
> I didn't understand that the second part

Thats not a big deal. https://www.lego.com/cdn/cs/set/assets/blt6879b00ae6951482/LEGO_MINDSTORMS_EV3_Communication_Developer_Kit.pdf  the protocol mentioned the length property. My fix is to read full packet instead the buffer. This is a common problem with all the serial communication and i think it's pretty clear.

**Comment by THEb0nny** [comment]
Хорошо, я тоже посмотрю, потом дам отзыв.
